2017-09-14T17:38:23.719Z - error: uncaughtException: "value" must be an object date=Thu Sep 14 2017 23:08:23 GMT+0530 (India Standard Time), pid=34852, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=61743104, heapTotal=46137344, heapUsed=33476928, external=18312694, loadavg=[0, 0, 0], uptime=89298.3710081, trace=[column=17, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\errors.js, function=Object.exports.process, line=140, method=process, native=false, column=25, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\any.js, function=internals.Any.validate, line=667, method=validate, native=false, column=62, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\jsonwebtoken\sign.js, function=Object.module.exports [as sign], line=76, method=exports [as sign], native=false, column=17, file=D:\All_Docs_Paresh\Documents\JWTokenProject\server.js, function=null, line=113, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongoose\lib\model.js, function=null, line=3832, method=null, native=false, column=21, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js, function=null, line=273, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js, function=null, line=131, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=73, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=104, method=_tickCallback, native=false], stack=[ValidationError: "value" must be an object,     at Object.exports.process (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\errors.js:140:17),     at internals.Any.validate (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\any.js:667:25),     at Object.module.exports [as sign] (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\jsonwebtoken\sign.js:76:62),     at D:\All_Docs_Paresh\Documents\JWTokenProject\server.js:113:17,     at Query.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongoose\lib\model.js:3832:16),     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js:273:21,     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js:131:16,     at _combinedTickCallback (internal/process/next_tick.js:73:7),     at process._tickCallback (internal/process/next_tick.js:104:9)]
2017-09-14T17:40:20.366Z - error: uncaughtException: "value" must be an object date=Thu Sep 14 2017 23:10:20 GMT+0530 (India Standard Time), pid=35176, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=61550592, heapTotal=46137344, heapUsed=33518480, external=18312700, loadavg=[0, 0, 0], uptime=89415.01968, trace=[column=17, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\errors.js, function=Object.exports.process, line=140, method=process, native=false, column=25, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\any.js, function=internals.Any.validate, line=667, method=validate, native=false, column=62, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\jsonwebtoken\sign.js, function=Object.module.exports [as sign], line=76, method=exports [as sign], native=false, column=17, file=D:\All_Docs_Paresh\Documents\JWTokenProject\server.js, function=null, line=113, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongoose\lib\model.js, function=null, line=3832, method=null, native=false, column=21, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js, function=null, line=273, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js, function=null, line=131, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=73, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=104, method=_tickCallback, native=false], stack=[ValidationError: "value" must be an object,     at Object.exports.process (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\errors.js:140:17),     at internals.Any.validate (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\any.js:667:25),     at Object.module.exports [as sign] (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\jsonwebtoken\sign.js:76:62),     at D:\All_Docs_Paresh\Documents\JWTokenProject\server.js:113:17,     at Query.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongoose\lib\model.js:3832:16),     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js:273:21,     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js:131:16,     at _combinedTickCallback (internal/process/next_tick.js:73:7),     at process._tickCallback (internal/process/next_tick.js:104:9)]
2017-09-14T17:42:25.101Z - error: uncaughtException: "value" must be an object date=Thu Sep 14 2017 23:12:25 GMT+0530 (India Standard Time), pid=35176, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=48586752, heapTotal=32505856, heapUsed=27100808, external=17929511, loadavg=[0, 0, 0], uptime=89539.747814, trace=[column=17, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\errors.js, function=Object.exports.process, line=140, method=process, native=false, column=25, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\any.js, function=internals.Any.validate, line=667, method=validate, native=false, column=62, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\jsonwebtoken\sign.js, function=Object.module.exports [as sign], line=76, method=exports [as sign], native=false, column=17, file=D:\All_Docs_Paresh\Documents\JWTokenProject\server.js, function=null, line=113, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongoose\lib\model.js, function=null, line=3832, method=null, native=false, column=21, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js, function=null, line=273, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js, function=null, line=131, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=73, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=104, method=_tickCallback, native=false], stack=[ValidationError: "value" must be an object,     at Object.exports.process (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\errors.js:140:17),     at internals.Any.validate (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\joi\lib\any.js:667:25),     at Object.module.exports [as sign] (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\jsonwebtoken\sign.js:76:62),     at D:\All_Docs_Paresh\Documents\JWTokenProject\server.js:113:17,     at Query.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongoose\lib\model.js:3832:16),     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js:273:21,     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\kareem\index.js:131:16,     at _combinedTickCallback (internal/process/next_tick.js:73:7),     at process._tickCallback (internal/process/next_tick.js:104:9)]
2017-09-15T09:39:02.323Z - error: uncaughtException: listen EADDRINUSE :::8080 date=Fri Sep 15 2017 15:09:01 GMT+0530 (India Standard Time), pid=42212, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=57851904, heapTotal=42991616, heapUsed=28807624, external=18197322, loadavg=[0, 0, 0], uptime=119879.035122, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=1020, method=_errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=1043, method=_exceptionWithHostPort, native=false, column=14, file=net.js, function=Server._listen2, line=1258, method=_listen2, native=false, column=10, file=net.js, function=listen, line=1294, method=null, native=false, column=5, file=net.js, function=Server.listen, line=1390, method=listen, native=false, column=24, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\express\lib\application.js, function=EventEmitter.listen, line=618, method=listen, native=false, column=5, file=D:\All_Docs_Paresh\Documents\JWTokenProject\server.js, function=null, line=240, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=579, method=.js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Module._load, line=438, method=_load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=389, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=149, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=504, method=null, native=false], stack=[Error: listen EADDRINUSE :::8080,     at Object.exports._errnoException (util.js:1020:11),     at exports._exceptionWithHostPort (util.js:1043:20),     at Server._listen2 (net.js:1258:14),     at listen (net.js:1294:10),     at Server.listen (net.js:1390:5),     at EventEmitter.listen (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\express\lib\application.js:618:24),     at Object.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\server.js:240:5),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:389:7),     at startup (bootstrap_node.js:149:9),     at bootstrap_node.js:504:3]
2017-09-15T09:39:04.401Z - error: uncaughtException: connection 0 to 127.0.0.1:27017 timed out date=Fri Sep 15 2017 15:09:04 GMT+0530 (India Standard Time), pid=42212, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=58822656, heapTotal=44040192, heapUsed=29580280, external=18205514, loadavg=[0, 0, 0], uptime=119881.1262416, trace=[column=11, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\error.js, function=Function.MongoError.create, line=29, method=create, native=false, column=20, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=198, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=338, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=386, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=250, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=214, method=listOnTimeout, native=false], stack=[MongoError: connection 0 to 127.0.0.1:27017 timed out,     at Function.MongoError.create (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\error.js:29:11),     at Socket.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\connection.js:198:20),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:338:8),     at ontimeout (timers.js:386:14),     at tryOnTimeout (timers.js:250:5),     at Timer.listOnTimeout (timers.js:214:5)]
2017-09-15T10:26:58.531Z - error: uncaughtException: Authentication failed. date=Fri Sep 15 2017 15:56:58 GMT+0530 (India Standard Time), pid=58176, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=59248640, heapTotal=44040192, heapUsed=29503696, external=18197954, loadavg=[0, 0, 0], uptime=122755.248632, trace=[column=11, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\error.js, function=Function.MongoError.create, line=31, method=create, native=false, column=72, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=497, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js, function=authenticateStragglers, line=443, method=null, native=false, column=5, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js, function=Connection.messageHandler, line=477, method=messageHandler, native=false, column=22, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=331, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=547, method=onread, native=false], stack=[MongoError: Authentication failed.,     at Function.MongoError.create (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\error.js:31:11),     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js:497:72,     at authenticateStragglers (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js:443:16),     at Connection.messageHandler (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js:477:5),     at Socket.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\connection.js:331:22),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:547:20)]
2017-09-15T10:40:04.686Z - error: uncaughtException: Authentication failed. date=Fri Sep 15 2017 16:10:04 GMT+0530 (India Standard Time), pid=57832, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=59301888, heapTotal=44040192, heapUsed=29512952, external=18197954, loadavg=[0, 0, 0], uptime=123541.4015974, trace=[column=11, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\error.js, function=Function.MongoError.create, line=31, method=create, native=false, column=72, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=497, method=null, native=false, column=16, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js, function=authenticateStragglers, line=443, method=null, native=false, column=5, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js, function=Connection.messageHandler, line=477, method=messageHandler, native=false, column=22, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=331, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=547, method=onread, native=false], stack=[MongoError: Authentication failed.,     at Function.MongoError.create (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\error.js:31:11),     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js:497:72,     at authenticateStragglers (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js:443:16),     at Connection.messageHandler (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\pool.js:477:5),     at Socket.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mongodb-core\lib\connection\connection.js:331:22),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:547:20)]
2017-09-15T16:15:50.955Z - error: uncaughtException: listen EADDRINUSE :::8080 date=Fri Sep 15 2017 21:45:50 GMT+0530 (India Standard Time), pid=4324, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.2, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=57950208, heapTotal=42991616, heapUsed=28779384, external=18197322, loadavg=[0, 0, 0], uptime=2561.8200946, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=1020, method=_errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=1043, method=_exceptionWithHostPort, native=false, column=14, file=net.js, function=Server._listen2, line=1258, method=_listen2, native=false, column=10, file=net.js, function=listen, line=1294, method=null, native=false, column=5, file=net.js, function=Server.listen, line=1390, method=listen, native=false, column=24, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\express\lib\application.js, function=EventEmitter.listen, line=618, method=listen, native=false, column=5, file=D:\All_Docs_Paresh\Documents\JWTokenProject\server.js, function=null, line=240, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=579, method=.js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Module._load, line=438, method=_load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=389, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=149, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=504, method=null, native=false], stack=[Error: listen EADDRINUSE :::8080,     at Object.exports._errnoException (util.js:1020:11),     at exports._exceptionWithHostPort (util.js:1043:20),     at Server._listen2 (net.js:1258:14),     at listen (net.js:1294:10),     at Server.listen (net.js:1390:5),     at EventEmitter.listen (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\express\lib\application.js:618:24),     at Object.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\server.js:240:5),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:389:7),     at startup (bootstrap_node.js:149:9),     at bootstrap_node.js:504:3]
2017-09-16T05:31:08.713Z - error: uncaughtException: listen EADDRINUSE :::8080 date=Sat Sep 16 2017 11:01:08 GMT+0530 (India Standard Time), pid=5848, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.3, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\server.js], rss=58564608, heapTotal=45121536, heapUsed=29862768, external=18219653, loadavg=[0, 0, 0], uptime=21256.8123869, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=1020, method=_errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=1043, method=_exceptionWithHostPort, native=false, column=14, file=net.js, function=Server._listen2, line=1258, method=_listen2, native=false, column=10, file=net.js, function=listen, line=1294, method=null, native=false, column=5, file=net.js, function=Server.listen, line=1390, method=listen, native=false, column=24, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\express\lib\application.js, function=EventEmitter.listen, line=618, method=listen, native=false, column=5, file=D:\All_Docs_Paresh\Documents\JWTokenProject\server.js, function=null, line=303, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=579, method=.js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Module._load, line=438, method=_load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=389, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=149, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=502, method=null, native=false], stack=[Error: listen EADDRINUSE :::8080,     at Object.exports._errnoException (util.js:1020:11),     at exports._exceptionWithHostPort (util.js:1043:20),     at Server._listen2 (net.js:1258:14),     at listen (net.js:1294:10),     at Server.listen (net.js:1390:5),     at EventEmitter.listen (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\express\lib\application.js:618:24),     at Object.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\server.js:303:5),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:389:7),     at startup (bootstrap_node.js:149:9),     at bootstrap_node.js:502:3]
2017-09-16T07:23:29.213Z - error: uncaughtException: expected { Object (domain, _events, ...) } to have status code 200 but got 500 date=Sat Sep 16 2017 12:53:28 GMT+0530 (India Standard Time), pid=13784, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.3, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mocha\bin\_mocha], rss=102825984, heapTotal=87085056, heapUsed=52332760, external=18037869, loadavg=[0, 0, 0], uptime=27997.3059211, trace=[column=33, file=D:\All_Docs_Paresh\Documents\JWTokenProject\test\test.js, function=chai.request.post.send.end, line=34, method=end, native=false, column=3, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js, function=Test.Request.callback, line=631, method=callback, native=false, column=18, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js, function=null, line=795, method=null, native=false, column=7, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\parsers\json.js, function=null, line=16, method=null, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=185, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=974, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=80, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=104, method=_tickCallback, native=false], stack=[AssertionError: expected { Object (domain, _events, ...) } to have status code 200 but got 500,     at chai.request.post.send.end (D:\All_Docs_Paresh\Documents\JWTokenProject\test\test.js:34:33),     at Test.Request.callback (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js:631:3),     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js:795:18,     at IncomingMessage.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\parsers\json.js:16:7),     at emitNone (events.js:91:20),     at IncomingMessage.emit (events.js:185:7),     at endReadableNT (_stream_readable.js:974:12),     at _combinedTickCallback (internal/process/next_tick.js:80:11),     at process._tickCallback (internal/process/next_tick.js:104:9)]
2017-09-16T07:26:16.063Z - error: uncaughtException: expected { Object (domain, _events, ...) } to have status code 200 but got 500 date=Sat Sep 16 2017 12:56:16 GMT+0530 (India Standard Time), pid=14936, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.3, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\mocha\bin\_mocha, --timeout, 10000], rss=85946368, heapTotal=68190208, heapUsed=47849904, external=18857824, loadavg=[0, 0, 0], uptime=28164.1514641, trace=[column=33, file=D:\All_Docs_Paresh\Documents\JWTokenProject\test\test.js, function=chai.request.post.send.end, line=34, method=end, native=false, column=3, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js, function=Test.Request.callback, line=631, method=callback, native=false, column=18, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js, function=null, line=795, method=null, native=false, column=7, file=D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\parsers\json.js, function=null, line=16, method=null, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=185, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=974, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=80, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=104, method=_tickCallback, native=false], stack=[AssertionError: expected { Object (domain, _events, ...) } to have status code 200 but got 500,     at chai.request.post.send.end (D:\All_Docs_Paresh\Documents\JWTokenProject\test\test.js:34:33),     at Test.Request.callback (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js:631:3),     at D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\index.js:795:18,     at IncomingMessage.<anonymous> (D:\All_Docs_Paresh\Documents\JWTokenProject\node_modules\superagent\lib\node\parsers\json.js:16:7),     at emitNone (events.js:91:20),     at IncomingMessage.emit (events.js:185:7),     at endReadableNT (_stream_readable.js:974:12),     at _combinedTickCallback (internal/process/next_tick.js:80:11),     at process._tickCallback (internal/process/next_tick.js:104:9)]
2017-09-16T08:39:51.366Z - error: uncaughtException: listen EADDRINUSE :::8080 date=Sat Sep 16 2017 14:09:50 GMT+0530 (India Standard Time), pid=5616, uid=null, gid=null, cwd=D:\All_Docs_Paresh\Documents\FinalJWTProject\JWTokenProject, execPath=C:\Program Files\nodejs\node.exe, version=v6.11.3, argv=[C:\Program Files\nodejs\node.exe, D:\All_Docs_Paresh\Documents\FinalJWTProject\JWTokenProject\server.js], rss=58691584, heapTotal=43024384, heapUsed=30445880, external=18422013, loadavg=[0, 0, 0], uptime=32579.4600053, trace=[column=11, file=util.js, function=Object.exports._errnoException, line=1020, method=_errnoException, native=false, column=20, file=util.js, function=exports._exceptionWithHostPort, line=1043, method=_exceptionWithHostPort, native=false, column=14, file=net.js, function=Server._listen2, line=1258, method=_listen2, native=false, column=10, file=net.js, function=listen, line=1294, method=null, native=false, column=5, file=net.js, function=Server.listen, line=1390, method=listen, native=false, column=24, file=D:\All_Docs_Paresh\Documents\FinalJWTProject\JWTokenProject\node_modules\express\lib\application.js, function=EventEmitter.listen, line=618, method=listen, native=false, column=5, file=D:\All_Docs_Paresh\Documents\FinalJWTProject\JWTokenProject\server.js, function=null, line=287, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=579, method=.js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Module._load, line=438, method=_load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=389, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=149, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=502, method=null, native=false], stack=[Error: listen EADDRINUSE :::8080,     at Object.exports._errnoException (util.js:1020:11),     at exports._exceptionWithHostPort (util.js:1043:20),     at Server._listen2 (net.js:1258:14),     at listen (net.js:1294:10),     at Server.listen (net.js:1390:5),     at EventEmitter.listen (D:\All_Docs_Paresh\Documents\FinalJWTProject\JWTokenProject\node_modules\express\lib\application.js:618:24),     at Object.<anonymous> (D:\All_Docs_Paresh\Documents\FinalJWTProject\JWTokenProject\server.js:287:5),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:389:7),     at startup (bootstrap_node.js:149:9),     at bootstrap_node.js:502:3]
